//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApi.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClienteCita
    {
        public int IDClienteCita { get; set; }
        public int IDCliente { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Estado { get; set; }
        public string Hora { get; set; }
    }
}
